### ISSUE TITLE
LoungeChair doesn't play nice with HiDPI screens

### ISSUE THREAD

**Issue by rctgamer3** [OatmealDome/LoungeChair#1]
Title. Unless I force-override the DPI set by the window, the entire window is blurry.

**Comment by OatmealDome** [comment]
Thanks for reporting. I don't use any HiDPI screens so I would've never caught this. Will attempt to fix in the next version.

**Comment by ShikiGami** [comment]
The problem is that this project is using WinForm, which has a lot of problems handling scaling.
I would recomend WPF for desktop applications. It handles scaling almost flawlessly, it uses DirectX for rendering, and is all along a better GUI library.

**Comment by DeltaJordan** [comment]
Actually the problem seems to be from CefSharp. The issue is addressed [here](https://github.com/cefsharp/CefSharp/issues/1571), [here](https://github.com/cefsharp/CefSharp/issues/1543) and [is addressed in WPF here](https://github.com/cefsharp/CefSharp/issues/1535). Switching to WPF will not solve the scaling issue from what I see.

**Comment by DeltaJordan** [comment]
After a bit of reading, this may fix it
https://github.com/cefsharp/CefSharp.MinimalExample/blob/master/CefSharp.MinimalExample.WinForms/Program.cs#L16
I'm not sure the exact value needed in the app.manifest; I will keep researching.

**Comment by DeltaJordan** [comment]
This should make the app dpi aware, and if its in Windows 8.1 or newer it should have dynamic dpi support.
```
  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>true/PM</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
```

**Comment by ShikiGami** [comment]
You can enable scaling on any GUI library if you tweek it enough, but the problem is that WinForms requieres a lot of more tweeking. The WPF recomendation comes because it does scaling almost without the need of tweeking it, and it is just a superior GUI library than WinForm in almost all aspects.
WinForm is actually deprecated, and it's actual use is intended to be for legacy aplications that created their whole GUI using it.
About the difference with scaling depending on the application, you can read [this](http://kynosarges.org/GuiDpiScaling.html)

**Comment by DeltaJordan** [comment]
I would need more info about which window is blurry, as rewriting this for WPF just because of the browser would not be worth it, but if the MainForm is also blurry, I may take on the task of rewriting it. I'm waiting for the decision on #3 before doing anything too drastic.

**Comment by OatmealDome** [comment]
@ShikiGami I have zero experience with WPF, and for an application as small as this, I am simply not willing to put in the time to learn and rewrite when I am busy with my personal life and 'actual' Switch things. Maybe @JordantheDewott would be willing to.

I am also not sure where you got your information that WinForms is deprecated. As far as I know, it is simply not receiving new features but is receiving bug fixes and minor improvements.

**Comment by rctgamer3** [comment]
LoungeChair is dead. Closing issue.
